### PR TITLE
Fix segfault in coll check

### LINKED ISSUE #188: Segmentation fault when running into tire wall
When driving/crashing in the Splatpack race "Figure of Hate" (16), I often get  a segmentation fault at the following location:

https://github.com/dethrace-labs/dethrace/blob/19ace40cb86a17f07239f9472b13b5ed963752bd/src/DETHRACE/common/car.c#L2818

```
(gdb) print car_spec->driver
$1 = eDriver_non_car

(gdb) print car_spec->power_up_levels
$2 = {45388384, 0, -559038737}
```
Does a non-car have power-up levels?

Short backtrace:
```
#0  0x000000000045d85d in CollCheck (c=0x2b475b0, dt=0.0399999991) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:2815
#1  0x00000000004344f2 in CollideCarWithWall (car=0x2b475b0, dt=0.0399999991) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:1347
#2  0x000000000048bb70 in CollideTwoCarsWithWalls (car1=0x1bafcd0, car2=0x2b475b0, dt=0.0399999991) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:5845
#3  0x000000000048a2cd in CrashCarsTogetherSinglePass (dt=0.0399999991, pPass=0, collide_list=0x7fffffffd900) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:5735
#4  0x0000000000487168 in CrashCarsTogether (dt=0.0399999991) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:5520
#5  0x00000000004324cc in ApplyPhysicsToCars (last_frame_time=38749, pTime_difference=16) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:1190
#6  0x000000000058bd15 in MainGameLoop () at /home/maarten/programming/dethrace/src/DETHRACE/common/mainloop.c:556
#7  0x000000000058cbde in DoRace () at /home/maarten/programming/dethrace/src/DETHRACE/common/mainloop.c:722
#8  0x00000000006b90f9 in DoGame () at /home/maarten/programming/dethrace/src/DETHRACE/common/structur.c:540
#9  0x00000000006b9a13 in DoProgram () at /home/maarten/programming/dethrace/src/DETHRACE/common/structur.c:647
#10 0x00000000005892d2 in GameMain (pArgc=2, pArgv=0x7fffffffdf18) at /home/maarten/programming/dethrace/src/DETHRACE/common/main.c:105
#11 0x000000000070c401 in original_main (pArgc=2, pArgv=0x7fffffffdf18) at /home/maarten/programming/dethrace/src/DETHRACE/pc-dos/dossys.c:664
#12 0x000000000070d0a2 in main (argc=2, argv=0x7fffffffdf18) at /home/maarten/programming/dethrace/src/DETHRACE/main.c:32
#13 0x00007ffff7229550 in __libc_start_call_main () at /lib64/libc.so.6
#14 0x00007ffff7229609 in __libc_start_main_impl () at /lib64/libc.so.6
```

<details>

<summary>Full backtrace</summary>

```
~"#0  0x000000000045d85d in CollCheck (c=0x2a969e8, dt=0.0399999991) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:2815\n"
~"        a = {v = {-593.983521, -10.290823, -28.7455196}}\n"
~"        a1 = {v = {-86.138237, -1.75013041, -4.19996786}}\n"
~"        aa = {v = {-85.921669, -1.69204903, -4.3219347}}\n"
~"        bb = {v = {0.949442983, 0.182803199, -0.949442983}}\n"
~"        cc = {v = {-0.223632812, -0.0890102386, -0.614330292}}\n"
~"        pos = {v = {-86.1382065, -1.73702359, -4.1910224}}\n"
~"        r = {{v = {0.462300032, 0.0890100077, 0.462300032}}, {v = {0.462300032, 0.0890100077, -0.462300032}}, {v = {-0.720599473, -0.448296696, 0.889374554}}, {v = {0.0896757841, 0.618216157, 0.380938411}}, {v = {-0.687509596, -53.8002243, -18.6166458}}, {v = {-64.8017426, -0.422515869, 0}}, {v = {0.906341553, 0, 1}}, {v = {0, -0.906341553, 0}}}\n"
~"        norm = {v = {0.896006286, 3.67827892, -0.912542462}}\n"
~"        n = {{v = {0, 1.62454116, 0}}, {v = {0, 2.05373764, 0}}, {v = {-0.115205839, 0.0918072015, -0.18622005}}, {v = {-0.786062121, 0.589359522, 0.812867343}}, {v = {0.21367757, 0.541751444, -0.551774383}}, {v = {0.580002427, 0.599176168, 0.13396509}}, {v = {-0.0722732395, 0.0401251689, 0.833097577}}, {v = {0.452059329, -0.318653822, -0.448296696}}}\n"
~"        dir = {v = {0.462300032, 0.0890100077, -0.0539430417}}\n"
~"        tv = {v = {11.1949549, 0.761470318, 3.42091084}}\n"
~"        tv2 = {v = {-0.469537109, 0.172549337, -3.03814697}}\n"
~"        tau = {{v = {-2.41914153, 0, 2.41914153}}, {v = {3.05826759, -0, 3.05826759}}, {v = {-0.0255832672, -3.96704102, 0.279799849}}, {v = {1.63989985, 2.48931054e-37, 0}}}\n"
~"        old_val = {v = {4.59163468e-41, 9.08745838e-39, 0}}\n"
~"        ftau = {v = {2.48931054e-37, 1.40129846e-45, -nan(0x7fd590)}}\n"
~"        max_friction = {v = {-0.698565781, -0, -0.169384226}}\n"
~"        vel = {v = {14.5694113, 0, 3.53270721}}\n"
~"        p_vel = {v = {0, 3.67827892, 0}}\n"
~"        normal_force = {v = {-0.0120568248, 0.03678279, -0.00426534889}}\n"
~"        friction_force = {v = {-1.20568252, 0, -0.426534891}}\n"
~"        d = {5.90910769, 6.49945354, -0.265756994, 0.0330724157}\n"
~"        f = {1.62454116, 2.05373764, 0.418412566, -0.116663903}\n"
~"        total_force = 3.67827892\n"
~"        point_vel = 0\n"
~"        batwick_length = 11.7307072\n"
~"        M = {m = {{7.92281055, 3.33333325, 0, 1.55081952}, {3.33333325, 7.92281055, -nan(0x7fd610), 2.04589576e-43}, {1.92349626e-38, 0, -nan(0x7fd740), 4.59163468e-41}, {-nan(0x7fd590), 4.59163468e-41, 7.34971376e-39, 2.40645069e-38}}}\n"
~"        dist = 2\n"
~"        ts = 51.6598167\n"
~"        ts2 = -0.00310329185\n"
~"        v_diff = -4.62405682\n"
~"        mat = 0x2893a0c\n"
~"        oldmat = 0x2a96a2c\n"
~"        mat_to_oldmat = {m = {{0.833097577, -0.448296696, 0.323941529}, {0.452059329, 0.889374554, 0.0681427419}, {-0.318653822, 0.0896757841, 0.943592966}, {0.406402588, -0.00142669678, -0.0277099609}}}\n"
~"        oldmat_to_mat = {m = {{0.833097577, 0.452059329, -0.318653822}, {-0.448296696, 0.889374554, 0.0896757841}, {0.323941529, 0.0681427419, 0.943592966}, {-0.0478595234, -0.0261699278, 0.0225741621}}}\n"
~"        tm = {m = {{-0.422515869, 0, -0.906341553}, {0, 1, 0}, {0.906341553, 0, -0.422515869}, {-224.451935, 12.0744734, -550.959717}}}\n"
~"        collision = 1\n"
~"        bnds = {min = {v = {-0.241265863, -0.0495505333, -0.0670000017}}, max = {v = {0.0670000017, 0.25850001, 0.130325899}}}\n"
~"        f_ref = 0xd17400 <gFace_list__car+576>\n"
~"        i = 2\n"
~"        j = 2\n"
~"        k = 2\n"
~"        material = 0\n"
~"        noise_defeat = 0\n"
~"        oldk = 2\n"
~"        min = 0.359999985\n"
~"        max = 0.439999998\n"
~"        edges = {{v = {-0.199021056, -0.138194576, 0.190574944}}, {v = {-0.0778656974, 0.273972303, 0.117348284}}, {v = {-0.142192945, 0.0176953543, -0.13566345}}}\n"
~"        corner = {v = {0.245600015, 0, -27.0648327}}\n"
~"        test_dir = {v = {0, 0, 0.134000003}}\n"
~"        message_mat = {m = {{0.982204616, 0.999974668, 0}, {0, -0.216271877, -0.00405681971}, {-0.520662427, 0, 100}, {4.59163468e-41, 6.08113647e-39, 0}}}\n"
~"        __FUNCTION__ = {67 'C', 111 'o', 108 'l', 108 'l', 67 'C', 104 'h', 101 'e', 99 'c', 107 'k', 0 '\\000'}\n"
~"        car_spec = 0x2a969e8\n"
~"#1  0x00000000004344f2 in CollideCarWithWall (car=0x2a969e8, dt=0.0399999991) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:1347\n"
~"        __FUNCTION__ = {67 'C', 111 'o', 108 'l', 108 'l', 105 'i', 100 'd', 101 'e', 67 'C', 97 'a', 114 'r', 87 'W', 105 'i', 116 't', 104 'h', 87 'W', 97 'a', 108 'l', 108 'l', 0 '\\000'}\n"
~"#2  0x000000000048bb70 in CollideTwoCarsWithWalls (car1=0xd1f890 <gProgram_state+176>, car2=0x2a969e8, dt=0.0399999991) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:5845\n"
~"        mom1 = {v = {1.9283683e-38, 0, -nan(0x7fd850)}}\n"
~"        mom2 = {v = {-4.28771162, 2.48945403e-37, 0}}\n"
~"        l = 0\n"
~"        m = 0\n"
~"        n = 1\n"
~"        p = 1\n"
~"        im1 = 0\n"
~"        im2 = 0\n"
~"        __FUNCTION__ = {67 'C', 111 'o', 108 'l', 108 'l', 105 'i', 100 'd', 101 'e', 84 'T', 119 'w', 111 'o', 67 'C', 97 'a', 114 'r', 115 's', 87 'W', 105 'i', 116 't', 104 'h', 87 'W', 97 'a', 108 'l', 108 'l', 115 's', 0 '\\000'}\n"
~"#3  0x000000000048a2cd in CrashCarsTogetherSinglePass (dt=0.0399999991, pPass=0, collide_list=0x7fffffffd900) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:5735\n"
~"        i = 0\n"
~"        j = 7\n"
~"        collided = 0\n"
~"        k = 32767\n"
~"        c1im = 1062803083\n"
~"        c2im = 0\n"
~"        car_1 = 0xd1f890 <gProgram_state+176>\n"
~"        car_2 = 0x2a969e8\n"
~"        car_3 = 0x3\n"
~"        car_in_middle = 0x7fffffffd9f0\n"
~"        car_on_wall = 0x33f591689\n"
~"        __FUNCTION__ = {67 'C', 114 'r', 97 'a', 115 's', 104 'h', 67 'C', 97 'a', 114 'r', 115 's', 84 'T', 111 'o', 103 'g', 101 'e', 116 't', 104 'h', 101 'e', 114 'r', 83 'S', 105 'i', 110 'n', 103 'g', 108 'l', 101 'e', 80 'P', 97 'a', 115 's', 115 's', 0 '\\000'}\n"
~"#4  0x0000000000487168 in CrashCarsTogether (dt=0.0399999991) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:5520\n"
~"        pass = 0\n"
~"        k = 45243152\n"
~"        i = 9\n"
~"        collide_list = {{ref = 1, car = 0x0}, {ref = 7, car = 0x0}, {ref = 7, car = 0x0}, {ref = 7, car = 0x0}, {ref = 7, car = 0x0}, {ref = 7, car = 0x0}, {ref = 7, car = 0x0}, {ref = 7, car = 0x0}, {ref = 8, car = 0x0}, {ref = 1064408964, car = 0x3cda12553ea835e3}, {ref = 1065334036, car = 0xbceb5686bea8cb87}, {ref = 1064407927, car = 0x4206cd00bfc2879c}, {ref = 1064408964, car = 0xbd1c8349bea8cb87}, {ref = 1065334036, car = 0x3d22a5293ea835e3}, {ref = 1064407927, car = 0xc1222fddbfc95861}, {ref = 1064408964, car = 0xbd1c8349bea8cb87}, {ref = 1065334036, car = 0x3f5a6a80bc29fa80}, {ref = -1030538206, car = 0xc2928ac7c1276ed8}, {ref = -1077323679, car = 0x3e7cd8893e7cd889}, {ref = 1122380179, car = 0xba9b691500000000}, {ref = -1100920910, car = 0x3e6147b2bed9168b}, {ref = 1051797183, car = 0x800000003f80006b}, {ref = 13732288, car = 0x2b25b10}, {ref = 1051764301, car = 0x300000000}, {ref = 1057026513, car = 0x2b25b10}, {ref = 45230844, car = 0x3f3b38a83f2dd947}, {ref = 0, car = 0x2b25b54}, {ref = 45243184, car = 0x2b25b48}, {ref = -9488, car = 0x43464c <CollideCarWithWall+1477>}, {ref = 0, car = 0x300000001}, {ref = 3, car = 0x2b22afc}, {ref = -9424, car = 0x433a38 <MoveAndCollideCar+1647>}}\n"
~"        __FUNCTION__ = {67 'C', 114 'r', 97 'a', 115 's', 104 'h', 67 'C', 97 'a', 114 'r', 115 's', 84 'T', 111 'o', 103 'g', 101 'e', 116 't', 104 'h', 101 'e', 114 'r', 0 '\\000'}\n"
~"#5  0x00000000004324cc in ApplyPhysicsToCars (last_frame_time=308075, pTime_difference=16) at /home/maarten/programming/dethrace/src/DETHRACE/common/car.c:1190\n"
~"        minus_k = {v = {4.59163468e-41, 6.11756883e-39, 0}}\n"
~"        i = 2\n"
~"        old_num_cars = 9\n"
~"        step_number = 1\n"
~"        dam_index = 30904701\n"
~"        steering_locked = 0\n"
~"        car = 0x2b25b10\n"
~"        car_info = 0x7fffffffdbb0\n"
~"        non_car = 0x2a94990\n"
~"        frame_end_time = 308091\n"
~"        __FUNCTION__ = {65 'A', 112 'p', 112 'p', 108 'l', 121 'y', 80 'P', 104 'h', 121 'y', 115 's', 105 'i', 99 'c', 115 's', 84 'T', 111 'o', 67 'C', 97 'a', 114 'r', 115 's', 0 '\\000'}\n"
~"#6  0x000000000058bd15 in MainGameLoop () at /home/maarten/programming/dethrace/src/DETHRACE/common/mainloop.c:556\n"
~"        camera_period = 16\n"
~"        start_menu_time = 0\n"
~"        frame_start_time = 30904701\n"
~"        result = eRace_game_abandonned\n"
~"        tried_to_allocate_AR = 1\n"
~"        i = 32767\n"
~"        bonus = 632039111\n"
~"        __FUNCTION__ = {77 'M', 97 'a', 105 'i', 110 'n', 71 'G', 97 'a', 109 'm', 101 'e', 76 'L', 111 'o', 111 'o', 112 'p', 0 '\\000'}\n"
~"#7  0x000000000058cbde in DoRace () at /home/maarten/programming/dethrace/src/DETHRACE/common/mainloop.c:722\n"
~"        result = eRace_game_abandonned\n"
~"        __FUNCTION__ = {68 'D', 111 'o', 82 'R', 97 'a', 99 'c', 101 'e', 0 '\\000'}\n"
~"#8  0x00000000006b90f9 in DoGame () at /home/maarten/programming/dethrace/src/DETHRACE/common/structur.c:540\n"
~"        options_result = eSO_continue\n"
~"        race_result = 32767\n"
~"        second_select_race = 1\n"
~"        first_summary_done = 30000\n"
~"        i = 0\n"
~"        __FUNCTION__ = {68 'D', 111 'o', 71 'G', 97 'a', 109 'm', 101 'e', 0 '\\000'}\n"
~"#9  0x00000000006b9a13 in DoProgram () at /home/maarten/programming/dethrace/src/DETHRACE/common/structur.c:647\n"
~"#10 0x00000000005892d2 in GameMain (pArgc=2, pArgv=0x7fffffffdf18) at /home/maarten/programming/dethrace/src/DETHRACE/common/main.c:105\n"
~"        CD_dir = {96 '`', -35 '\\335', -1 '\\377', -1 '\\377', -1 '\\377', 127 '\\177', 0 '\\000', 0 '\\000', -96 '\\240', -36 '\\334', -1 '\\377', -1 '\\377', -1 '\\377', 127 '\\177', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', -128 '\\200', -23 '\\351', -102 '\\232', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', -128 '\\200', 0 '\\000', -128 '\\200', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 115 's', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 24 '\\030', -33 '\\337', -1 '\\377', -1 '\\377', -1 '\\377', 127 '\\177', 0 '\\000', 0 '\\000', -96 '\\240', -30 '\\342', -1 '\\377', -9 '\\367', -1 '\\377', 127 '\\177', 0 '\\000', 0 '\\000', -112 '\\220', -35 '\\335', -1 '\\377', -1 '\\377', -1 '\\377', 127 '\\177', 0 '\\000', 0 '\\000', 10 '\\n', -49 '\\317', 114 'r', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 123 '{', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 123 '{', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 2 '\\002', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 24 '\\030', -33 '\\337', -1 '\\377', -1 '\\377', -1 '\\377', 127 '\\177', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000', 0 '\\000'...}\n"
~"#11 0x000000000070c401 in original_main (pArgc=2, pArgv=0x7fffffffdf18) at /home/maarten/programming/dethrace/src/DETHRACE/pc-dos/dossys.c:664\n"
~"        arg = 14028560\n"
~"        i = 2\n"
~"        f = 4.59163468e-41\n"
~"#12 0x000000000070d0a2 in main (argc=2, argv=0x7fffffffdf18) at /home/maarten/programming/dethrace/src/DETHRACE/main.c:32\n"
~"#13 0x00007ffff7229550 in __libc_start_call_main () at /lib64/libc.so.6\n"
~"#14 0x00007ffff7229609 in __libc_start_main_impl () at /lib64/libc.so.6\n"
~"#15 0x0000000000403b25 in _start ()\n"
^done
```

</details>

### PR DESCRIPTION
**Pull request by madebr**
Fixes #188

### CODE REVIEW

File: src/DETHRACE/common/car.c [hunk 1]
```diff
@@ -5593,161 +5584,153 @@ int CrashCarsTogetherSinglePass(br_scalar dt, int pPass, tCollison_data* collide
                             collide_list[i].car = car_2;
                             collided++;
                         }
-                    } else if (collide_list[i].car || collide_list[j].car) {
```
Comment (dethrace-labs) [inline src/DETHRACE/common/car.c:5596]: I'm not sure how comfortable I feel with this large scale refactoring. On one hand the proposed code for sure looks more sensible, but I don't think I can look at the changes hard enough to know that we haven't introduced a subtle strange behavior. And rewriting the flow makes it very difficult to go back and step through following the OG code in a debugger. 

I actually don't know how to handle this. One idea is to wait until the single player game is (more or less) complete before cleaning the code up too much, and hopefully at that time we aren't comparing OG code? Do we break the PR into two? Everything above this line is easy to merge right now. What do you think?

Comment (madebr) [reply src/DETHRACE/common/car.c:5596]: This is no refactoring, it's the same code with less indentations.

Comment (madebr) [reply src/DETHRACE/common/car.c:5596]: But I'll remove the indentation patch to a separate pr.

**Review by dethrace-labs — APPROVED** [review]
