### PR TITLE
Networking #1 - Lobby implemented

### LINKED ISSUE #326: Segfault when running dethrace with --enable-diagnostics
`gDiagnostic_file` is potentially used unitialized in `dr_dprintf`.

## Reproducer

Start dethrace with `--enable-diagnostics`.

```
Stack trace:
0: ?? ??:0
1: ?? ??:0
2: dr_dprintf at /home/maarten/projects/dethrace/src/DETHRACE/common/errors.c:252
3: PDBuildAppPath at /home/maarten/projects/dethrace/src/DETHRACE/pc-win95/win95sys.c:681
4: GameMain at /home/maarten/projects/dethrace/src/DETHRACE/common/main.c:112
5: original_main at /home/maarten/projects/dethrace/src/DETHRACE/pc-win95/win95sys.c:950
6: main at /home/maarten/projects/dethrace/src/DETHRACE/main.c:35
7: ?? ??:0
8: ?? ??:0
```

### PR DESCRIPTION
**Pull request by dethrace-labs**
- Server can host a game, client can discover the host and join the game
- Added `win95net.c` to hold all the windows-specific network code
- Moved dos specific stuff into `dosnet`
Screenshot 2023-07-03 at 3 35 26 pm

Fixes #326

### CODE REVIEW

File: src/DETHRACE/dr_types.h [hunk 1]
```diff
@@ -3839,265 +3350,256 @@ typedef struct tGroovidelic_spec {             // size: 0x80
...
-
-typedef struct tPD_net_game_info {
-    _IPX_LOCAL_TARGET addr_ipx;
-    tU32 last_response;
-} tPD_net_game_info;
-
-typedef struct tIPX_netnum {
-    unsigned char bNetwork[4];
-} tIPX_netnum;
+// typedef struct DWORDREGS {
```
Comment (madebr) [inline src/DETHRACE/dr_types.h:3353]: Do `#if 0` instead, that results in a smaller diff.

File: src/DETHRACE/pc-win95/win95net.c [hunk 2]
```diff
@@ -0,0 +1,676 @@
...
+    return 999;
+}
+
+int SameEthernetAddress(struct sockaddr_in* pAddr_ipx1, struct sockaddr_in* pAddr_ipx2) {
+    LOG_TRACE("(%p, %p)", pAddr_ipx1, pAddr_ipx2);
+
+    return memcmp(pAddr_ipx1, pAddr_ipx2, sizeof(struct sockaddr_in)) == 0;
+}
+
+/*SOCKADDR_IPX_* */ void GetIPXAddrFromPlayerID(tPlayer_ID pPlayer_id) {
```
Comment (madebr) [inline src/DETHRACE/pc-win95/win95net.c:133]: It's not implemented atm, but does it return a pointer?
```suggestion
/*SOCKADDR_IPX_* */ void* GetIPXAddrFromPlayerID(tPlayer_ID pPlayer_id) {
```

File: src/DETHRACE/pc-win95/win95net.c [hunk 3]
```diff
@@ -0,0 +1,676 @@
...
+int GetMessageTypeFromMessage(char* pMessage_str) {
+    char* real_msg;
+    int msg_type_int;
+    LOG_TRACE("(\"%s\")", pMessage_str);
+
+    real_msg = &pMessage_str[4];
+    msg_type_int = 0;
+
+    // FIXME: "CW95MSG" value is used in and depends on platform
+    if (strncmp(real_msg, "CW95MSG", gMsg_header_strlen) == 0) {
```
Comment (madebr) [inline src/DETHRACE/pc-win95/win95net.c:116]: The comment should probably move to another location.
```suggestion
    // FIXME: "CW95MSG" value is used in and depends on platform
    if (strncmp(real_msg, MESSAGE_HEADER_STR, gMsg_header_strlen) == 0) {
```

File: src/DETHRACE/pc-win95/win95net.c [hunk 4]
```diff
@@ -0,0 +1,676 @@
...
+    int already_registered;
+    LOG_TRACE("()");
+
+    char addr_string[32];
+    unsigned int sa_len;
+    int wsa_error;
+
+    sa_len = sizeof(gRemote_addr);
+    while (1) {
+        if (recvfrom(gSocket, gReceive_buffer, 512, 0, (struct sockaddr*)&gRemote_addr, &sa_len) == -1) {
```
Comment (madebr) [inline src/DETHRACE/pc-win95/win95net.c:163]:
```suggestion
        if (recvfrom(gSocket, gReceive_buffer, sizeof(gReceive_buffer), 0, (struct sockaddr*)&gRemote_addr, &sa_len) == -1) {
```

File: src/DETHRACE/pc-win95/win95net.c [hunk 5]
```diff
@@ -0,0 +1,676 @@
...
+            already_registered = 0;
+            for (i = 0; i < gNumber_of_hosts; i++) {
+                if (SameEthernetAddress(&gJoinable_games[i].addr_in, gRemote_addr_ipx)) {
+                    already_registered = 1;
+                    break;
+                }
+            }
+            if (already_registered) {
+                dr_dprintf("That game already registered");
+                gJoinable_games[i].last_response = PDGetTotalTime();
```
Comment (madebr) [inline src/DETHRACE/pc-win95/win95net.c:181]: I **think** the logic is something like this:
```c
while (1) {
    // ...
    if (SameEthernetAddress(gLocal_addr_ipx, gRemote_addr_ipx)) {
        dr_dprintf("*** Discounting the above 'cos we sent it ***");
        continue;
    }
    if (GetMessageTypeFromMessage(gReceive_buffer) != 2) {
        dr_dprintf("*** Discounting the above 'cos it's not a host reply ***");
        continue;
    }
    dr_dprintf(s_***_It's_a_host_reply!_***_00511054);
    // ...
}
```

File: src/DETHRACE/pc-win95/win95net.c [hunk 6]
```diff
@@ -0,0 +1,676 @@
...
+
+    // // IPX broadcast
+    // gBroadcast_addr_ipx->sa_nodenum[0] = -1;
+    // gBroadcast_addr_ipx->sa_nodenum[1] = -1;
+    // gBroadcast_addr_ipx->sa_nodenum[2] = -1;
+    // gBroadcast_addr_ipx->sa_nodenum[3] = -1;
+    // gBroadcast_addr_ipx->sa_nodenum[4] = -1;
+    // gBroadcast_addr_ipx->sa_nodenum[5] = -1;
+
+    gLocal_addr.sin_family = AF_INET;
```
Comment (madebr) [inline src/DETHRACE/pc-win95/win95net.c:288]: When `AF_INET6`? :rofl:

File: src/DETHRACE/pc-win95/win95net.c [hunk 7]
```diff
@@ -0,0 +1,676 @@
...
+
+    // gSocket = socket(6, 2, 1000);
+    gSocket = socket(AF_INET, SOCK_DGRAM, 0);
+    if (gSocket == -1) {
+        dr_dprintf("PDNetInitialise(): Failed to create socket - WSAGetLastError=%d", WSAGetLastError());
+        WSACleanup();
+        return -1;
+    }
+    char broadcast = '1';
+    setsockopt(gSocket, SOL_SOCKET, SO_BROADCAST, &broadcast, sizeof(broadcast));
```
Comment (madebr) [inline src/DETHRACE/pc-win95/win95net.c:310]: Are you sure this is a char? OG uses an int, with value 1 instead of `'1'`.

File: src/DETHRACE/pc-win95/win95net.c [hunk 8]
```diff
@@ -0,0 +1,676 @@
...
+}
+
+// IDA: void __cdecl PDNetStartProducingJoinList()
+void PDNetStartProducingJoinList(void) {
+    LOG_TRACE("()");
+
+    dr_dprintf("PDNetStartProducingJoinList()");
+    gNumber_of_hosts = 0;
+    gJoinable_games = BrMemAllocate(sizeof(tPD_net_game_info) * JOINABLE_GAMES_CAPACITY, 0x80u);
+    if (!gJoinable_games) {
```
Comment (madebr) [inline src/DETHRACE/pc-win95/win95net.c:396]:
```suggestion
    if (gJoinable_games == NULL) {
```

File: src/DETHRACE/pc-win95/win95net.c [hunk 9]
```diff
@@ -0,0 +1,676 @@
...
+
+// IDA: void __cdecl PDNetEndJoinList()
+void PDNetEndJoinList(void) {
+    LOG_TRACE("()");
+
+    dr_dprintf("PDNetEndJoinList()");
+    if (gJoinable_games) {
+        BrMemFree(gJoinable_games);
+    }
+    gJoinable_games = 0;
```
Comment (madebr) [inline src/DETHRACE/pc-win95/win95net.c:409]:
```suggestion
    gJoinable_games = NULL;
```

File: src/DETHRACE/pc-win95/win95net.c [hunk 10]
```diff
@@ -0,0 +1,676 @@
...
+    LOG_TRACE("(%p)", pDetails);
+
+    dr_dprintf("PDNetHostFinishGame()");
+}
+
+// IDA: tU32 __usercall PDNetExtractGameID@<EAX>(tNet_game_details *pDetails@<EAX>)
+tU32 PDNetExtractGameID(tNet_game_details* pDetails) {
+    LOG_TRACE("(%p)", pDetails);
+
+    return ntohs(pDetails->pd_net_info.addr_in.sin_port); // PDGetTotalTime();
```
Comment (madebr) [inline src/DETHRACE/pc-win95/win95net.c:495]:
```suggestion
    dr_dprintf("PDNetExtractGameID()");
    return ntohs(pDetails->pd_net_info.addr_in.sin_port); // PDGetTotalTime();
```

File: src/DETHRACE/pc-win95/win95net.c [hunk 11]
```diff
@@ -0,0 +1,676 @@
...
+}
+
+// IDA: tPlayer_ID __usercall PDNetExtractPlayerID@<EAX>(tNet_game_details *pDetails@<EAX>)
+tPlayer_ID PDNetExtractPlayerID(tNet_game_details* pDetails) {
+    LOG_TRACE("(%p)", pDetails);
+
+    return ntohs(gLocal_addr_ipx->sin_port);
```
Comment (madebr) [inline src/DETHRACE/pc-win95/win95net.c:502]:
```suggestion
    dr_dprintf("PDNetExtractPlayerID()");
    return ntohs(gLocal_addr_ipx->sin_port);
```

File: src/DETHRACE/pc-win95/win95net.c [hunk 12]
```diff
@@ -0,0 +1,676 @@
...
+    }
+    while (1) {
+        pName = strpbrk(pName, "_=(){}[]<>!$%^&*/:@~;'#,?\\|`\"");
+        if (*pName == '\0') {
+            break;
+        }
+        *pName = '-';
+    }
+#else
+    strcpy(pName, "Ron Turn");
```
Comment (madebr) [inline src/DETHRACE/pc-win95/win95net.c:534]: Perhaps add a FIXME here? Because this can return system specific information.
Windows has `GetComputerNameA`, Linux has `gethostname()` and macos has probably also something.

File: src/DETHRACE/pc-win95/win95net.c [hunk 13]
```diff
@@ -0,0 +1,676 @@
...
+// IDA: int __usercall PDNetSendMessageToAllPlayers@<EAX>(tNet_game_details *pDetails@<EAX>, tNet_message *pMessage@<EDX>)
+int PDNetSendMessageToAllPlayers(tNet_game_details* pDetails, tNet_message* pMessage) {
+    char str[256];
+    int i;
+    LOG_TRACE("(%p, %p)", pDetails, pMessage);
+
+    for (i = 0; i < gNumber_of_net_players; ++i) {
+        if (i == gThis_net_player_index) {
+            continue;
+        }
```
Comment (madebr) [inline src/DETHRACE/pc-win95/win95net.c:555]: I see a function call here, returning a `tNet_game_player_info *` here.

**Review by madebr — COMMENTED** [review]
Awesome work!

File: src/DETHRACE/common/main.c [hunk 14]
```diff
@@ -107,9 +107,10 @@ void ServiceGameInRace(void) {
 void GameMain(int pArgc, char** pArgv) {
     tPath_name CD_dir;
 
+    OpenDiagnostics();
+
     PDSetFileVariables();
     PDBuildAppPath(gApplication_path);
-    OpenDiagnostics();
```
[the remark this answers is not in the document]
Comment (dethrace-labs) [reply src/DETHRACE/common/main.c:112]: good spotting, thanks. Our particular implementation of `dr_dprintf` assumed `gDiagnostics_file` would always be initialized. But `PDBuildAppPath` calls `dr_dprintf` before `OpenDiagnostics` is called. I was being lazy and just moved it so I could see the diagnostics messages.

I think the right fix, looking at the one `DIAGNOST.TXT` captured in the wild (http://1amstudios.com/articles/reactivating-carmageddon-debug-output/) is to return out of `dr_dprintf` if the file is not yet opened. The file in the link above doesn't contain a line for the path that should have been printed from `PDBuildAppPath`

**Comment by madebr** [comment]
I *think* the build fails [because of this](https://stackoverflow.com/questions/1372480/c-redefinition-header-files-winsock2-h).
We need to include `winsock2.h` before `windows.h`.

File: src/DETHRACE/common/network.c [hunk 15]
```diff
@@ -287,14 +628,63 @@ int NetJoinGame(tNet_game_details* pDetails, char* pPlayer_name, int pCar_index)
...
+#if !defined(DETHRACE_FIX_BUGS)
+            // Avoid double free
+            NetDisposeGameDetails(gCurrent_net_game);
+#endif
+            gCurrent_net_game = NULL;
+            if (gJoin_request_denied) {
+                result = -1;
+            } else {
+                result = -2;
+            }
```
[the remark this answers is not in the document]
Comment (dethrace-labs) [reply src/DETHRACE/common/network.c:677]: wow, this was a good spot!

File: src/DETHRACE/pc-win95/win95net.c (hunk 13 above)
Comment (dethrace-labs) [reply src/DETHRACE/pc-win95/win95net.c:552]: You mean a call to a function from inside the for loop? I double checked all the `call` instructions, I don't see any extra ones?

File: src/DETHRACE/pc-win95/win95net.c (hunk 12 above)
Comment (dethrace-labs) [reply src/DETHRACE/pc-win95/win95net.c]: meant to do this before I PR'd. Done now

File: src/DETHRACE/pc-win95/win95net.c (hunk 13 above)
Comment (madebr) [reply src/DETHRACE/pc-win95/win95net.c:543]: You're right.
I mixed this one with `PDNetSendMessageToPlayer`.

File: src/DETHRACE/common/network.c [hunk 16]
```diff
@@ -223,22 +384,77 @@ void NetDisposePlayer(tNet_game_player_info* pPlayer) {
...
+        eDriver_net_human,
+        pPlayer->car,
+        pPlayer->car_index,
+        pPlayer->player_name,
+        &gNet_cars_storage_space);
+    if (switched_res) {
+        SwitchToLoresMode();
+    }
+    InitialiseCar(pPlayer->car);
+    if (pPlayer->player_status < 6) {
```
[the remark this answers is not in the document]
Comment (dethrace-labs) [reply src/DETHRACE/common/network.c]: It should be comparing against `ePlayer_status_racing` I believe

File: src/DETHRACE/common/network.c [hunk 17]
```diff
@@ -45,7 +45,7 @@ int gRace_only_flags[33] = {
 };
 int gJoin_list_mode;
 tNet_game_player_info gNew_net_players[6];
-tGuaranteed_message gGuarantee_list[150];
+tGuaranteed_message gGuarantee_list[100]; // DOS debug symbols has this as [150]
```
Comment (madebr) [inline src/DETHRACE/common/network.c:48]: Perhaps they increased it for carmageddon 2.
I found functions in carmageddon 2 that are present in these debug symbols, but not in the carmageddon 1 executables.

File: .github/scripts/build-msvc.ps1 [hunk 18]
```diff
@@ -18,7 +20,13 @@ Expand-Archive $Env:TEMP\SDL2-devel.zip -DestinationPath $Env:TEMP
 
 # build
 cmake -G Ninja -DCMAKE_BUILD_TYPE=RelWithDebInfo -DBUILD_TESTS=ON "-DSDL2_ROOT_DIR=$($Env:TEMP)\SDL2-$sdl2_version" -B build
+if ($LASTEXITCODE -ne 0) {
```
Comment (madebr) [inline .github/scripts/build-msvc.ps1:23]: Since last week, SDL has https://github.com/libsdl-org/setup-sdl to set-up SDL2/3 in github actions.
It's still experimental, but works very well for cmake projects.

**Review by madebr — APPROVED** [review]

File: .github/scripts/build-msvc.ps1 (hunk 18 above)
Comment (dethrace-labs) [reply .github/scripts/build-msvc.ps1:23]: cool, adding an issue to look at using it 👍
