### PR TITLE
Disable invalid groove bindings at end of LoadCar()

### LINKED ISSUE #178: Lady Bug and Sinthea crash game on race start
Repro:

1. download Carmageddon files from GoG.com
2. run 0.4 release with splat pack files
3. start new game
4. if one of racers will be Lady Bug, game will crash on start

__Note that this behavior was also crashing the original game.__ So either car needs fixing/workaround for it needs to be implemented or it needs to be prevented from running in races.

https://user-images.githubusercontent.com/750553/192165524-51b1d533-6982-4b79-a063-0018afe73246.mp4

### PR DESCRIPTION
**Pull request by madebr**
Fixes #178 

For more background;
https://www.cwaboard.co.uk/viewtopic.php?p=158796

### CODE REVIEW

File: src/DETHRACE/common/loading.c [hunk 1]
```diff
@@ -2285,6 +2285,42 @@ void LoadCar(char* pCar_name, tDriver pDriver, tCar_spec* pCar_spec, int pOwner,
     }
     fclose(f);
     fclose(g);
+
+#if DETHRACE_FIX_BUGS
+#define CHECK_BINDING_INDEX(IDX)                                                                                 \
+    do {                                                                                                         \
+        if ((IDX) >= 0) {                                                                                        \
+            if (gGroove_funk_bindings[IDX] == NULL) {                                                            \
```
Comment (dethrace-labs) [inline src/DETHRACE/common/loading.c:2293]: or if `IDX > COUNT_OF(gGroove_funk_bindings)` ?

Comment (madebr) [reply src/DETHRACE/common/loading.c:2293]: No, the issue was not out-of-bounds access, but dereferencing a null pointer inside the `gGroove_funk_bindings` array.

Comment (madebr) [reply src/DETHRACE/common/loading.c:2293]:
```suggestion
            if (IDX >= COUNT_OF(gGroove_funk_bindings) || gGroove_funk_bindings[IDX] == NULL) {                                                            \
```

**Review by dethrace-labs — APPROVED** [review]
