### PR TITLE
Fixes memory out of bounds with shaking rearview camera

### LINKED ISSUE #522: Totaling/crashing two opponents at/around the same time using The Twister causes a game crash
Happened while I newly obtained "The Twister". I was playing the Wall Street Crash level.
Steps to recreate:

- Make sure you're going at a high speed to total your opponents while having "The Twister".

### PR DESCRIPTION
**Pull request by dethrace-labs**
Fixes #522 by fixing two ASAN errors - one unrelated in `TestForNan` and one by ensuring the rearview mirror doesn't get drawn off screen even in large collisions (called `wobbles` in code)

### CODE REVIEW

File: src/DETHRACE/common/graphics.c [hunk 1]
```diff
@@ -2074,6 +2074,11 @@ void RenderAFrame(int pDepth_mask_on) {
         }
         gRearview_screen->base_x = gScreen_wobble_x + gProgram_state.current_car.mirror_left;
         gRearview_screen->base_y = gScreen_wobble_y + gProgram_state.current_car.mirror_top;
+#ifdef DETHRACE_FIX_BUGS
+        gRearview_screen->base_x = MAX(0, gRearview_screen->base_x);
+        gRearview_screen->base_y = MAX(0, gRearview_screen->base_y);
```
Comment (madebr) [inline src/DETHRACE/common/graphics.c]: Both are unsigned integers, so can never be negative.
I can still reproduce a crash with the twister with this pr.

Comment (madebr) [reply src/DETHRACE/common/graphics.c]: This patch does the job for me:
```patch
--- a/src/DETHRACE/common/graphics.c
+++ b/src/DETHRACE/common/graphics.c
@@ -2072,11 +2072,12 @@ void RenderAFrame(int pDepth_mask_on) {
         if (gVoodoo_rush_mode >= 1) {
             gRearview_screen->pixels = gBack_screen->pixels;
         }
+#ifdef DETHRACE_FIX_BUGS
+        gRearview_screen->base_x = MAX(0, gScreen_wobble_x + gProgram_state.current_car.mirror_left);
+        gRearview_screen->base_y = MAX(0, gScreen_wobble_y + gProgram_state.current_car.mirror_top);
+#else
         gRearview_screen->base_x = gScreen_wobble_x + gProgram_state.current_car.mirror_left;
         gRearview_screen->base_y = gScreen_wobble_y + gProgram_state.current_car.mirror_top;
-#ifdef DETHRACE_FIX_BUGS
-        gRearview_screen->base_x = MAX(0, gRearview_screen->base_x);
-        gRearview_screen->base_y = MAX(0, gRearview_screen->base_y);
 #endif
 
 #endif
```

Comment (dethrace-labs) [reply src/DETHRACE/common/graphics.c]: Thanks for the double check. I had it like you suggested originally then did “just a little refactor” and committed. :)
