### PR TITLE
Use DOS code for in-menu car icons

### LINKED ISSUE #339: Car icons are drawn wrong in race synchronization menu in hires mode
In lores mode, they are drawn correctly.

image

My Carmageddon data folder contains the following `CARICONS.PIX` files:
```
./DATA/PIXELMAP/CARICONS.PIX
./DATA/64X48X8/PIXELMAP/CARICONS.PIX
```

Removing `./DATA/64X48X8/PIXELMAP/CARICONS.PIX` fixes it for dethrace,
and replacing `./DATA/PIXELMAP/CARICONS.PIX` with `./DATA/64X48X8/PIXELMAP/CARICONS.PIX` breaks it for the OG dos carmageddon version.

### PR DESCRIPTION
**Pull request by madebr**
Fixes #339

### CODE REVIEW

**Review by dethrace-labs — APPROVED** [review]

File: src/DETHRACE/common/netgame.c [hunk 1]
```diff
@@ -417,12 +418,24 @@ void InitNetHeadups(void) {
...
+    } else {
+        gIcons_pix_low_res = gIcons_pix;
+    }
 }
 
 // IDA: void __cdecl DisposeNetHeadups()
 void DisposeNetHeadups(void) {
     LOG_TRACE("()");
 
+    if (gIcons_pix_low_res != NULL && gIcons_pix_low_res != gIcons_pix) {
```
Comment (madebr) [inline src/DETHRACE/common/netgame.c:435]:
```suggestion
    /* Windows version does not use gIcons_pix_low_res. */
    if (gIcons_pix_low_res != NULL && gIcons_pix_low_res != gIcons_pix) {
```
