### PR TITLE
input: use PDKeyDown3 in PDGetASCIIFromKey

### LINKED ISSUE #321: Holding down SHIFT makes key repeat go crazy quick
In places where you can enter text, such as the Driver Selection menu or Save Game menu, when you hold down the <kbd>SHIFT</kbd> key while entering text, the text is repeated very fast.

## How to reproduce

1. Start a new game
2. Click on one of the drivers
3. Remove all text using backspace
4. Hold down the <kbd>SHIFT</kbd> (with your pink)
5. Press any other letter key

## Expected result

The letter is entered, with a moderate speed

## Actual result

The complete input box is filled with the letter

### PR DESCRIPTION
**Pull request by madebr**
PDKeyDown3 does not modify last_key_down and last_key_down_time

`PDKeyDown3` is used in the german DOS Carmageddon executable,
but not in the GOG splatpack Windows executable.

So I'm unsure what the correct approach is here.

Fixes #321

### CODE REVIEW

File: src/DETHRACE/pc-win95/win95sys.c [hunk 1]
```diff
@@ -308,7 +308,7 @@ void Win32ReleaseInputDevice(void) {
 int PDGetASCIIFromKey(int pKey) {
     LOG_TRACE("(%d)", pKey);
 
-    if (PDKeyDown(KEY_SHIFT_ANY)) {
+    if (PDKeyDown3(KEY_SHIFT_ANY)) {
```
Comment (dethrace-labs) [inline src/DETHRACE/pc-win95/win95sys.c:311]: lets put a comment here describing why we are deviating from the OG windows code

**Comment by dethrace-labs** [comment]
Interesting! I didn't look at the german executables at all :)

I think generally our approach should be to take the best implementation parts from all the different executables to provide the 'best' experience.

As long as we comment where and why we are deviating from the default OG source, I think its fine :)

**Review by dethrace-labs — APPROVED** [review]

File: src/DETHRACE/pc-win95/win95sys.c (hunk 1 above)
Comment (madebr) [inline src/DETHRACE/pc-win95/win95sys.c:311]:
```suggestion
    /* The Windows Carmageddon executable uses PDKeyDown here. The German DOS executable uses PDKeyDown3. */
    if (PDKeyDown3(KEY_SHIFT_ANY)) {
```
