### PR TITLE
Dispose track after race + get german localization running

### LINKED ISSUE #99: German and demo version support broken?
When trying to use the German disc version as a data dir with a current git checkout the game fails with the following message:

```
DETHRACE_ROOT_DIR: /media/cdrom/
[INFO] Harness_DetectGameMode "Carmageddon"
[WARN] SoundService stubbed
[WARN] NetService stubbed
dprintf: FATAL ERROR: This .exe must have KEYBOARD.COK in the DATA folder.
FATAL ERROR: This .exe must have KEYBOARD.COK in the DATA folder.
```

The file indeed doesn't seem to be available, also when installing the game. On the other hand I can see variable names with `GERMAN` in their name, so I assume the version should be supported?

(Something may be wrong with the detection mechanism in general, or I'm doing something completely wrong: I also couldn't start the _Original Carmageddon demo_ or the _Splat Pack demo_ linked from the GitHub page...)

### LINKED ISSUE #110: Latest commit crashes build on Manjaro
Hello All!

Lately the build is not working on Linux : 

Error:
Consolidate compiler generated dependencies of target harness
[ 49%] Building C object src/harness/CMakeFiles/harness.dir/os/linux.c.o
/home/csabesz/Documents/dethrace/src/harness/os/linux.c:20:10: fatal error: sys/sysctl.h: No such file or directory
   20 | #include <sys/sysctl.h>
      |          ^~~~~~~~~~~~~~
compilation terminated.

### PR DESCRIPTION
**Pull request by madebr**
This pr:
- implements `DisposeTrack` (+depending functions). It is now possible to start a 2nd race in the same DethRace execution
- implement functions to support localized carmageddon releases: tested with a German localization
- fixes demo + text input for demo's

@laenion Can you test this?
The german version has the following issues:
- In all races, the HUD is hidden behind terrain (uk version also has this problem in e.g. fridge racer)
- in maim street, the front culling is too aggressive (the terrain is shown too late)

There is also a visual glitch with the umlaut on "neues spiel über netzwerk".
Comparing the data structures sizing the interface, there appears to be no difference between the uk and german release.
Is this also present when running the windows/dos version?
(the umlaut remains visible when changing the active menu item)

~The splatpack + xmas demo version stil do not work.~

Screenshot from 2022-03-20 19-03-59

Closes #99
Closes #110

### CODE REVIEW

**Comment by laenion** [comment]
Your branch is crashing with a segmentation fault for me; I'll have a more detailed look at it in the evening. Just in case you see something immediately:

```
DETHRACE_ROOT_DIR: /home/gamer/CARMA/
[INFO] Harness_DetectGameMode "Carmageddon"
[WARN] BrSystemConfigBegin stubbed
[WARN] HostImageLoad stubbed
[WARN] SoundService stubbed
[WARN] NetService stubbed

******************
Caught SIGSEGV
******************

Stack trace:
0: ?? ??:0
1: ?? ??:0
2: ?? ??:0
3: GetThreeInts at /home/gamer/dethrace/src/DETHRACE/common/loading.c:2835
4: LoadGeneralParameters at /home/gamer/dethrace/src/DETHRACE/common/loading.c:346
5: InitialiseApplication at /home/gamer/dethrace/src/DETHRACE/common/init.c:345
6: InitialiseDeathRace at /home/gamer/dethrace/src/DETHRACE/common/init.c:407
7: GameMain at /home/gamer/dethrace/src/DETHRACE/common/main.c:98
8: original_main at /home/gamer/dethrace/src/DETHRACE/pc-dos/dossys.c:667
9: main at /home/gamer/dethrace/src/DETHRACE/main.c:29
10: ?? ??:0
11: ?? ??:0
```

It didn't want to accept the disc contents directly due to missing write permissions, so `DETHRACE_ROOT_DIR` is directing to a full installation of the game now.

**Comment by laenion** [comment]
Hmmm... Now it complains about

```
[INFO] Harness_DetectGameMode "Carmageddon"
[INFO] Harness_DetectGameMode Language: "German"
[WARN] BrSystemConfigBegin stubbed
[WARN] HostImageLoad stubbed
[WARN] SoundService stubbed
[WARN] NetService stubbed
[WARN] DefaultNetSettings stubbed
[WARN] BrTokenValueSetMany stubbed
[WARN] BrTokenValueSetMany stubbed
[WARN] BrTokenValueSetMany stubbed
[WARN] BrDevLastBeginQuery stubbed
FATAL ERROR: Unable to find required palette
```

**Comment by madebr** [comment]
Strange, my german carmageddon data directory should not be different from yours.
I simply copied the complete CD to hd (I'm not using an installed folder).
Are you perhaps running dethrace in an installed carmageddon folder?
Also, what system are you running?


The error is emitted in the [`InitializePalettes`](https://github.com/dethrace-labs/dethrace/blob/b339af2cdfe7fb6c6d9130597edabe0c7e2e7ea3/src/DETHRACE/common/graphics.c#L611) function.
The actual loading of the palette happens in [`LoadInRegisteeDir`](https://github.com/dethrace-labs/dethrace/blob/b339af2cdfe7fb6c6d9130597edabe0c7e2e7ea3/src/DETHRACE/common/loading.c#L657).
If you add a [debug breakpoint here](https://github.com/dethrace-labs/dethrace/blob/b339af2cdfe7fb6c6d9130597edabe0c7e2e7ea3/src/DETHRACE/common/loading.c#L562), it should encounter `DRRENDER.PAL` and `DRACEFLC.PAL`.

**Comment by laenion** [comment]
Yes, for the previous test I was using an installed version of Carmageddon (I thought that was necessary), but now I also just copied the contents from disc.

The result is still the same though (plus two warnings about _PATHS.TXT_ and _OPTIONS.TXT_ not being found). The interesting thing is that `DRLoadPalette` (at least that's where I thing you wanted to link to) never seems to be reached. It aborts in https://github.com/madebr/dethrace/blob/dispose-track/src/DETHRACE/common/graphics.c#L617 instead.

I'm using the madebr/dispose-track branch - I assume that is the branch you are also testing with?

**Comment by madebr** [comment]
The warnings about `PATHS.TXT` `OPTIONS.TXT` are expected. I have them too and the game loads fine.
DethRace expects the `OPTIONS.TXT` file to be encoded, which it isn't. It falls back to default options.
The `PATHS.TXT` warning is a consequence of `OPTIONS.TXT` not being found.

The breakpoint is not hit because it can't find those palette files.
To be clear, you need to set the `DETHRACE_ROOT_DIR` to the directory containing the carmageddon exe's, not the DATA directory.
```sh
export DETHRACE_ROOT_DIR=/directory/to/german/carmageddon

```
The following command must contain `DRRENDER.PAL` and `DRACEFLC.PAL`.
If not, you need to do 2 things: 1. check whether the copy was complete and 2. check the `DETHRACE_ROOT_DIR` environment variable.
```
ls $DETHRACE_ROOT_DIR/DATA/REG/PALETTES
```

You can simply run dethrace by executing:
```sh
/path/to/dethrace
```

If it is still failing, can you tell a bit more about your system? OS? Filesystem? Is it case sensitive?

File: src/DETHRACE/common/flicplay.c [hunk 1]
```diff
@@ -1365,30 +1397,33 @@ int LoadFlic(int pIndex) {
...
-        strcpy(gLast_flic_name, gMain_flic_list[pIndex].file_name);
-        fclose(f);
-        return 1;
-    } else {
+    if (gMain_flic_list[pIndex].data_ptr == NULL) {
         if (AllocationErrorsAreFatal()) {
             FatalError(14, gMain_flic_list[pIndex].file_name);
         }
+#ifdef DETHRACE_FIX_BUGS
+        fclose(f);
```
Comment (dethrace-labs) [inline src/DETHRACE/common/flicplay.c:1412]: is this to make the compiler happy?

File: src/harness/harness.c [hunk 2]
```diff
@@ -34,25 +34,141 @@ tHarness_game_info harness_game_info;
...
+            harness_game_info.mode = eGame_carmageddon_demo;
+            LOG_INFO("\"%s\"", "Carmageddon demo");
+        }
+        else {
+            goto carmageddon;
+        }
     } else {
-        harness_game_info.defines.INTRO_SMK_FILE = "MIX_INTR.SMK";
+carmageddon:
+        if (access("DATA/CURSCENE/Mix_intr.smk", F_OK) == -1) {
```
Comment (dethrace-labs) [inline src/harness/harness.c:118]: `CURSCENE` should be `CUTSCENE`?

Also, do we need this now we've fixed the case sensitive file access?

Comment (madebr) [reply src/harness/harness.c:118]: Indeed, can be collapsed into one.

Comment (madebr) [reply src/harness/harness.c:118]: And the `INTO_SMK_FILE` variable can be set unconditionally

Comment (madebr) [reply src/harness/harness.c:118]: And the `INTO_SMK_FILE` variable can be set unconditionally

File: src/DETHRACE/common/flicplay.c (hunk 1 above)
Comment (madebr) [reply src/DETHRACE/common/flicplay.c:1412]: Not really.
If allocation errors are not fatal, this code path can leak.
Very unlikely, I know.

File: src/harness/harness.c (hunk 2 above)
Comment (madebr) [reply src/harness/harness.c:118]: I need to patch `smk_open_file` for that.
It looks like that file has already been customized.

Comment (madebr) [inline src/harness/harness.c:118]:
```suggestion
        if (access("DATA/CUTSCENE/Mix_intr.smk", F_OK) == -1) {
```
